const SESSION_ID = "SADIYA-MD=y9xT2Qha#DZSAcFIYKrdAk6poelr-QmKPdpZw6nP0LPXHjfJHhPM"
const GITHUB_USER_NAME = "franco43-free"
const GITHUB_AUTH_TOKEN = ""
const DATABASE_REPO_NAME = "SADIYA-MD-DATABASE"

module.exports = {SESSION_ID,GITHUB_USER_NAME,GITHUB_AUTH_TOKEN,DATABASE_REPO_NAME}
